// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvJvsLqA0bywhOzVUGEJwr6TGOOOpYKMU',
    appId: '1:605665085334:web:4e05e8aa2929d5c8f43fb7',
    messagingSenderId: '605665085334',
    projectId: 'roadvision-6aea7',
    authDomain: 'roadvision-6aea7.firebaseapp.com',
    databaseURL: 'https://roadvision-6aea7-default-rtdb.firebaseio.com',
    storageBucket: 'roadvision-6aea7.firebasestorage.app',
    measurementId: 'G-Z8V5P0X9ZK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDobq5xPqBIAA_ns9jgISC9zXyz-crue2I',
    appId: '1:605665085334:android:f0ec3da3331b88e1f43fb7',
    messagingSenderId: '605665085334',
    projectId: 'roadvision-6aea7',
    databaseURL: 'https://roadvision-6aea7-default-rtdb.firebaseio.com',
    storageBucket: 'roadvision-6aea7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV29OwV213t4O1KY6e06Qpl2ZB6CEaino',
    appId: '1:605665085334:ios:e40d1224bfc0ce0cf43fb7',
    messagingSenderId: '605665085334',
    projectId: 'roadvision-6aea7',
    databaseURL: 'https://roadvision-6aea7-default-rtdb.firebaseio.com',
    storageBucket: 'roadvision-6aea7.firebasestorage.app',
    iosBundleId: 'com.example.roadvision',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBV29OwV213t4O1KY6e06Qpl2ZB6CEaino',
    appId: '1:605665085334:ios:e40d1224bfc0ce0cf43fb7',
    messagingSenderId: '605665085334',
    projectId: 'roadvision-6aea7',
    databaseURL: 'https://roadvision-6aea7-default-rtdb.firebaseio.com',
    storageBucket: 'roadvision-6aea7.firebasestorage.app',
    iosBundleId: 'com.example.roadvision',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvJvsLqA0bywhOzVUGEJwr6TGOOOpYKMU',
    appId: '1:605665085334:web:983a9ef23f7240f5f43fb7',
    messagingSenderId: '605665085334',
    projectId: 'roadvision-6aea7',
    authDomain: 'roadvision-6aea7.firebaseapp.com',
    databaseURL: 'https://roadvision-6aea7-default-rtdb.firebaseio.com',
    storageBucket: 'roadvision-6aea7.firebasestorage.app',
    measurementId: 'G-QBY5SPJ0TD',
  );

}